apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gpu-inference
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gpu-inference
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gpu-inference
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - {}
